spring:
  datasource:
    url: jdbc:mariadb://one-more-db.csefzcm41p8j.ap-northeast-2.rds.amazonaws.com:3306/one_more
    username: admin
    password: onemore1!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
        format_sql: true
  devtools:
    livereload:
      enabled: true
  profiles:
    include: oauth
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

